#!/usr/bin/perl

# vmrp-clone - VMware Resource Pool Clone
#
# Authors:
#   Thomas Liske <liske@ibh.de>
#
# Copyright Holder:
#   2011 (C) IBH IT-Service GmbH [http://www.ibh.de/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use strict;
use warnings;

use VMware::VIRuntime;
use XML::Simple;

my %opts = (
   fn => {
      type => "=s",
      help => "XML resource pool config input filename (vmrp-clone)",
      required => 1,
   },
   lwpsslver => {
      type => "=i",
      help => "Disable/enable SSL certificate verification (LWP).",
      default => 0,
   },
);

Opts::add_options(%opts);
Opts::parse();
Opts::validate();

$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = Opts::get_option('lwpsslver');

Util::connect();

$|++;

my $xs = XML::Simple->new(RootName => 'vmrp-clone', ForceArray => qw(VM));
my $config = $xs->XMLin(Opts::get_option('fn'));

my @vm_clusters = @{Vim::find_entity_views(view_type => 'ClusterComputeResource')};

my $i;
do {
    print STDERR "\nSelect cluster:\n";
    print STDERR   "===============\n";

    $i = 0;
    foreach (@vm_clusters) {
	print STDERR " [", ++$i, "] ", $_->name, "\n";
    }

    print STDERR "\n> ";

    chomp($i = <>);
    $i = int($i);
} while($i<1 || $i>$#vm_clusters+1);
$i--;
my $cluster = $vm_clusters[$i];

my @rpools = ($cluster->resourcePool);
sub get_rpools($$) {
    my $rp = Vim::get_view(mo_ref => shift);
    my $ident = shift || '';
    my $name = $rp->name;

    print STDERR "${ident}[$#rpools] $name\n";

    if(defined($rp->resourcePool)) {
	foreach my $crp (@{$rp->resourcePool}) {
	    &get_rpools($crp, "$ident ");
	}
    }
}

print STDERR "\nRetrieving resource pools:\n";
print STDERR   "==========================\n";

get_rpools($cluster->resourcePool, '');


# disconnect from the server
Util::disconnect();
